// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOSExampleApplication
{
	public partial class DashboardViewController : UIViewController
	{
		public String _usernameDashboard { get; set; }
		
		public DashboardViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);
			// username.Text = _usernameDashboard;
		}
	}
}
