// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOSExampleApplication
{
	public partial class DashboardViewController : UIViewController
	{
		public String _usernameDashboard { get; set; }
		
		public DashboardViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			keyboardBtn.Layer.CornerRadius = 12;
			keyboardBtn.Layer.BorderWidth = 1; 
			keyboardBtn.Layer.BorderColor = UIColor.Blue.CGColor;
		}
		
		public override void ViewWillAppear(bool animated)
		{
			var usernameLabel = new UILabel
			{
				Frame = new CGRect(16, 105, 300, 40),
				Text = _usernameDashboard,
				TextColor = UIColor.Black
			};

			View.AddSubview(usernameLabel);
		}
		
	}
}
