// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOSExampleApplication
{
	public partial class KeyboardViewController : UIViewController
	{
		public KeyboardViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
